### ISSUE TITLE
Is bee-queue for me?

### ISSUE THREAD

**Issue by thelinuxlich** [LewisJEllis/bee-queue#17]
I will need a heavy processing queue(thousands of jobs per second), no need to respond to the requestor.

**Comment by LewisJEllis** [comment]
The queue itself is extremely performance-focused and is certainly capable of handling thousands of jobs per second, especially if you have more than one worker. How many it can handle is pretty much a function of how fast your Redis is and how many workers you have. All the overhead of responding to the requestor can be removed by setting `getEvents` and `sendEvents` to false, and you can keep Redis memory from ballooning by setting `removeOnSuccess` to true. 

One case where bee-queue might not be performance-optimal is if you ever have several jobs to enqueue at the same time from the same source; it'll make a separate Redis pipeline for each job enqueued, but could theoretically enqueue multiple jobs on one pipeline. If this would be useful, it's certainly not out of the question to add it.

**Comment by thelinuxlich** [comment]
Hmm, I think I didn't understand what you're saying about several jobs to enqueue at the same time from the same source. Do you mean the common use case where a producer sends at least a job per request always to the same queue?

**Comment by LewisJEllis** [comment]
I mean if, say, a request comes in to a producer, and it knows immediately that it wants to create not just one but 5 jobs as a result of that request. They're all being created effectively at the same time, but this would be done with 5 pipelines (and thus 5 roundtrips). It could theoretically be done with just one if there was some way to give bee-queue 5 jobs at once and have it send them together.

If you just send one job per request, it sounds like you line right up with the second of my target use cases outlined at the top of https://github.com/LewisJEllis/bee-queue/wiki/Origin, but if you might send multiple from one request, then there's this room for improvement. I'm not completely sure how much room, but there's room nonetheless. My guess is that if most of your jobs usually come in groups of ~4 or more, it could be a worthwhile improvement.

**Comment by thelinuxlich** [comment]
oh okay, that's not my case!

**Comment by thelinuxlich** [comment]
I'm just afraid the payload can be higher than 100kb sometimes

**Comment by LewisJEllis** [comment]
More than 100kb is not in and of itself necessarily a problem - it's kind of a guideline to avoid using too much memory on Redis. There are certainly scenarios where 100kB can be a reasonably payload, especially if only from time to time, but if it's regularly much more than that and you have high job throughput, you might risk running into a spike where Redis runs out of memory. Smaller payloads help avoid this, but if you're aware of the risk and have considered it, there's no major problem with bigger payloads.
