### ISSUE TITLE
[FIX] Job status not updated

### ISSUE THREAD

**Issue by v4l3r10** [LewisJEllis/bee-queue#19]
Hi!
i saw that when job complete or failed the status field isn't updated with new value;)
{"data":{},"options":{"timeout":20000},"status":"created"}

**Comment by LewisJEllis** [comment]
Closed by #20

**Comment by patriceperez** [comment]
If I understand correctly then this fix should be included in v0.3.0, however I am still encountering this issue.

did I miss something?

**Comment by v4l3r10** [comment]
no Patrice this fix is not included in 0.3.0. 
It was released 1 month after!

see here https://github.com/LewisJEllis/bee-queue/commits/master

**Comment by patriceperez** [comment]
@v4l3r10 
oh I see... thank you for the quick reply! sorry for the confusion
