### ISSUE TITLE
Question on `removeOnSuccess`

### ISSUE THREAD

**Issue by davisford** [LewisJEllis/bee-queue#28]
If I have a producer and a consumer for a queue, let's say I set it up as follows:

`producer`

```javascript
var producerQueue = new Queue('foo', {
  isWorker: false,
  removeOnSuccess: true
};
```

`consumer`

```javascript
var consumerQueue = new Queue('foo', {
  isWorker: true
};
```

I've noticed that when I configure it this way, after a job completes, and I check Redis, even though a job has finished successfully, the job data still exists.  The docs aren't clear with respect to the `removeOnSuccess` prop -- does it need to be set on the producer queue or the consumer queue, or both?

**Comment by davisford** [comment]
It appears through trial it should be with the worker/consumer.  If you set `removeOnSuccess` on the producer queue, it has no effect...but I figured I'd ask you, and maybe a good point for updating the docs?

**Comment by LewisJEllis** [comment]
Yep, good catch. It should be set on the consumer, since it's possible that the producer never hears about the job's completion (if the producer has `getEvents` disabled). I'll clarify that in the docs.
