### ISSUE TITLE
Date objects are not preserved

### ISSUE THREAD

**Issue by matteocontrini** [LewisJEllis/bee-queue#32]
When a job data or a job result contains a `Date` object, the `JSON.stringify` call converts that Date object in an ISO string.
For example: `2015-12-23T16:55:59.956Z`.

The problem is that when the data is parsed later with `JSON.parse`, that string is not converted back into a `Date` object, because JSON doesn't have a Date type.

[This fork](https://github.com/LewisJEllis/bee-queue/compare/master...matteocontrini:master) would solve the issue adding a custom parser. But: 1) it could affect performance 1) if an ISO date string is originally passed as data, it will be automatically converted to a `Date` instance.

If it's fine, a PR can be created.

**Comment by matteocontrini** [comment]
Another solution would be to use a custom replacer for `JSON.stringify`, which would create a string representation of the `Date` object, with some kind of flags that says "this was a Date object". In this way, when the custom parser is called, only the *true* `Date`s will be converted.

**Comment by LewisJEllis** [comment]
https://github.com/LewisJEllis/bee-queue#properties-1 does specify that the `data` passed should be json-serializable, but the use case is compelling.

The most proper way to fix this would be to use [msgpack](http://msgpack.org/index.html) or something similar that can accurately retain type information. I'm not sure that I want to introduce such a dependency, but binary encoding is a significant upgrade over JSON for a number of reasons. I'll give this some thought.

For now, I would suggest storing your dates as numeric timestamps.

**Comment by matteocontrini** [comment]
Ok, thanks for the reply.
I'll try to handle the conversion in my code :)

**Comment by matteocontrini** [comment]
For those who might need to do that conversion, here is a recursive function that modified the JavaScript object in place:

```js
var convertDates = function(obj) {
	for (var key in obj) {
		if (obj.hasOwnProperty(key)) {
			var value = obj[key];
			
			if (typeof value == 'object') {
				obj[key] = convertDates(value);
			}
			else if (/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:[.,]\d+)?Z/i.test(value)) {
				obj[key] = new Date(value);
			}
		}
	}
}
```
