### ISSUE TITLE
How to enqueue of a job purely from redis for nginx

### ISSUE THREAD

**Issue by nitzanav** [LewisJEllis/bee-queue#59]
Hi,

I wish to create jobs directly from nginx using a redis [module for nginx](https://github.com/openresty/redis2-nginx-module).

I am looking for something similar to what [sidekiq wik](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby)i provides.

Can someone assist in listing the redis operations to be done?

**Comment by LewisJEllis** [comment]
It's done via the [addJob lua script](https://github.com/LewisJEllis/bee-queue/blob/master/lib/lua/addJob.lua) which is invoked via [EVALSHA](https://redis.io/commands/evalsha) in the [Job#save](https://github.com/LewisJEllis/bee-queue/blob/master/lib/job.js#L42) method.

**Comment by nitzanav** [comment]
thank you, amazing 

what is the right way to raise some questions or a short discussion regarding alternatives for improvements? is it via issue in github?
